CREATE TABLE CLIENTE(
	CODCLI INT,
	NOMECLI VARCHAR(50),
	TELEFONECLIENTE VARCHAR(40),
	CPFCLI VARCHAR(20),
	PRIMARY KEY(CODCLI)
);
CREATE TABLE VEICULO(
	CODVEI INT, 
	MODELO VARCHAR(50), 
	MARCA VARCHAR(50), 
	PLACA VARCHAR(20),
	CODCLI INT,
	PRIMARY KEY(CODVEI),
	FOREIGN KEY(CODCLI) REFERENCES CLIENTE(CODCLI)
);
CREATE TABLE TIPO_DE_SERVICO(
	CODTIPO INT,
	NOMETIPO VARCHAR(50),
	DESCRICAOTIPO VARCHAR(50),
	PRECOTIPO FLOAT,
	PRIMARY KEY(CODTIPO)
);
CREATE TABLE FUNCIONARIO(
	CODFUNC INT,
	NOMEFUNC VARCHAR(50),
	SALARIOFUNC FLOAT,
	PRIMARY KEY(CODFUNC)
);
CREATE TABLE FORNECEDOR(
	CODFOR INT,
	NOMEFOR VARCHAR(50),
	CNPJFOR VARCHAR(50),
	PRIMARY KEY(CODFOR)
);
CREATE TABLE MATERIAL(
	CODMAT INT,
	NOMEMAT VARCHAR(50),
	DESCRICAOMAT VARCHAR(50),
	PRECOMAT FLOAT,
	CODFOR INT,
	PRIMARY KEY(CODMAT),
	FOREIGN KEY(CODFOR) REFERENCES FORNECEDOR(CODFOR)
);
CREATE TABLE SERVICO(
	CODSER INT,
	DESCRICAOSER VARCHAR(50),
	DATAINI DATE,
	DATAFIM DATE,
	PRIMARY KEY(CODSER),
	CODTIPO INT,
	CODVEI INT,
	CODCLI INT,
	FOREIGN KEY(CODTIPO) REFERENCES TIPO_DE_SERVICO(CODTIPO),
	FOREIGN KEY(CODVEI) REFERENCES VEICULO(CODVEI),
	FOREIGN KEY(CODCLI) REFERENCES CLIENTE(CODCLI)
);
CREATE TABLE FUNCIONARIO_SERVICO(
	CODFUNC INT,
	CODSER INT,
	PRIMARY KEY(CODFUNC, CODSER),
	FOREIGN KEY(CODFUNC) REFERENCES FUNCIONARIO(CODFUNC),
	FOREIGN KEY(CODSER) REFERENCES SERVICO(CODSER)
);
CREATE TABLE SERVICO_MATERIAL(
	CODSER INT,
	CODMAT INT,
	QUANTIDADE INT,
	PRIMARY KEY(CODSER, CODMAT),
	FOREIGN KEY(CODSER) REFERENCES SERVICO(CODSER),
	FOREIGN KEY(CODMAT) REFERENCES MATERIAL(CODMAT)
);
